name: Deploy Gradio App to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create and Push to Hugging Face Space
      run: |
        # Computer ko naam aur email batate hain
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        # Hum yahan 'origin' ka address badal rahe hain, naya nahi bana rahe
        git remote set-url origin https://AmitCseR:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/AmitCseR/My-First-AI-App
        
        # Is command se code hamesha 'main' branch me hi jayega
        git push --force origin HEAD:main