name: Deploy Gradio App to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create and Push to Hugging Face Space
      run: |
        # Computer ko naam aur email batate hain
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        # Hum yahan se seedha code bhejenge, koi extra folder nahi banayenge
        git init
        git remote add origin https://AmitCseR:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/AmitCseR/My-First-AI-App
        
        # Sab kuch (app.py, requirements.txt, etc.) add karte hain
        git add .
        git commit -m "Deploying final version of the app"

        # Is command se code hamesha 'main' branch me hi jayega
        git push --force origin HEAD:maingit