# Yeh file hamare app ko Hugging Face Spaces par deploy karegi
name: Deploy Gradio App to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install gradio transformers torch

    - name: Create and Push to Hugging Face Space
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        
        mkdir -p .huggingface/
        echo '{"models": ["image-classification"]}' > .huggingface/README.md
        cp app.py .huggingface/
        cd .huggingface/
        git init
        # Humne neeche waali line ko badla hai taaki password seedha address me chala jaye
        git remote add origin https://${{ github.repository_owner }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ github.repository }}
        git add .
        git commit -m "Initial Gradio app deploy"
        git push --force origin master